# Generated by Django 4.0.3 on 2022-04-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender_id', models.IntegerField()),
                ('receiver_id', models.IntegerField()),
                ('text', models.TextField()),
                ('attachment_audio_url', models.TextField(null=True)),
                ('attachment_image_url', models.TextField(null=True)),
                ('attachment_video_url', models.TextField(null=True)),
                ('attachment_document_url', models.TextField(null=True)),
            ],
        ),
    ]
