# Generated by Django 4.0.3 on 2022-04-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('firmware_version', models.FloatField()),
                ('date_of_purcahse', models.DateField()),
                ('serial_number', models.CharField(max_length=100)),
                ('mac_address', models.CharField(max_length=100, null=True)),
                ('machine_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('measurement_id', models.IntegerField(primary_key=True, serialize=False)),
                ('device_id', models.IntegerField()),
                ('patient_id', models.IntegerField()),
                ('assigner_id', models.IntegerField()),
                ('machine_id', models.IntegerField()),
                ('date_assigned', models.DateField()),
                ('date_returned', models.DateField()),
                ('measurement', models.FloatField()),
            ],
        ),
    ]
