# Generated by Django 4.0.3 on 2022-04-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firebase_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
